kind: pipeline
type: docker
name: Deploy Website

steps:
  - name: Rebuild Website
    image: docker
    commands:
      - apk update
      - apk upgrade
      - apk add --no-cache git
      - docker compose -f docker-compose.website-prod.yml --project-name website up -d --force-recreate --build
      # - tail -f /dev/null
    environment:
      NODE_ENV:
        from_secret: NODE_ENV
      DOCKER_HOST:
        from_secret: DOCKER_HOST
      DOCKER_BUILDKIT:
        from_secret: DOCKER_BUILDKIT
      NEXT_PUBLIC_DNS_DOMAIN:
        from_secret: NEXT_PUBLIC_DNS_DOMAIN
      NEXT_PUBLIC_KEYCLOAK_URL:
        from_secret: NEXT_PUBLIC_KEYCLOAK_URL
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID:
        from_secret: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
      REDDIT_BOT_TOKEN:
        from_secret: REDDIT_BOT_TOKEN
      REDDIT_BOT_SECRET:
        from_secret: REDDIT_BOT_SECRET
      REDDIT_BOT_ID:
        from_secret: REDDIT_BOT_ID
      DISCORD_CLIENT_ID:
        from_secret: DISCORD_CLIENT_ID
      DISCORD_CLIENT_TOKEN:
        from_secret: DISCORD_CLIENT_TOKEN

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: WEBHOOK_ID
      webhook_token:
        from_secret: WEBHOOK_TOKEN
      avatar_url: https://i.imgur.com/tnw3I34.png
      username: 'Drone CI'
      message: |
        {{#success build.status}}
        Build {{build.number}} succeeded.
        {{else}}
        Build {{build.number}} failed.
        {{/success}}
        Build time: {{build.started}}
        Commit message: {{commit.message}}
        Commit author: {{commit.author}}
        Commit branch: {{commit.branch}}
        {{#success build.status}}
        View logs: <{{build.link}}>
        {{else}}
        View failed job: <{{build.link}}>
        {{/success}}

trigger:
  branch:
  - main
trigger:
  event:
  # - cron
  - custom
  - push
  # - pull_request
  # - tag
  # - promote
  # - rollback